// Project imports:
import 'package:network_arch/dns_lookup/utils/rr_code_name.dart';

rrCodeName rrCodeToName(int type) {
  switch (type) {
    case 1:
      return rrCodeName.A;
    case 10:
      return rrCodeName.NULL;
    case 28:
      return rrCodeName.AAAA;
    case 18:
      return rrCodeName.AFSDB;
    case 42:
      return rrCodeName.APL;
    case 257:
      return rrCodeName.CAA;
    case 60:
      return rrCodeName.CDNSKEY;
    case 59:
      return rrCodeName.CDS;
    case 37:
      return rrCodeName.CERT;
    case 5:
      return rrCodeName.CNAME;
    case 49:
      return rrCodeName.DHCID;
    case 32769:
      return rrCodeName.DLV;
    case 39:
      return rrCodeName.DNAME;
    case 48:
      return rrCodeName.DNSKEY;
    case 43:
      return rrCodeName.DS;
    case 55:
      return rrCodeName.HIP;
    case 13:
      return rrCodeName.HINFO;
    case 45:
      return rrCodeName.IPSECKEY;
    case 25:
      return rrCodeName.KEY;
    case 36:
      return rrCodeName.KX;
    case 29:
      return rrCodeName.LOC;
    case 15:
      return rrCodeName.MX;
    case 35:
      return rrCodeName.NAPTR;
    case 2:
      return rrCodeName.NS;
    case 47:
      return rrCodeName.NSEC;
    case 50:
      return rrCodeName.NSEC3;
    case 51:
      return rrCodeName.NSEC3PARAM;
    case 12:
      return rrCodeName.PTR;
    case 46:
      return rrCodeName.RRSIG;
    case 17:
      return rrCodeName.RP;
    case 24:
      return rrCodeName.SIG;
    case 6:
      return rrCodeName.SOA;
    case 99:
      return rrCodeName.SPF;
    case 33:
      return rrCodeName.SRV;
    case 44:
      return rrCodeName.SSHFP;
    case 32768:
      return rrCodeName.TA;
    case 249:
      return rrCodeName.TKEY;
    case 52:
      return rrCodeName.TLSA;
    case 250:
      return rrCodeName.TSIG;
    case 16:
      return rrCodeName.TXT;
    case 252:
      return rrCodeName.AXFR;
    case 251:
      return rrCodeName.IXFR;
    case 41:
      return rrCodeName.OPT;
    case 255:
      return rrCodeName.ANY;
  }

  return rrCodeName.UNKNOWN;
}
