String rrTypeToString(int type) {
  switch (type) {
    case 1:
      return 'A';
    case 10:
      return 'NULL';
    case 28:
      return 'AAAA';
    case 18:
      return 'AFSDB';
    case 42:
      return 'APL';
    case 257:
      return 'CAA';
    case 60:
      return 'CDNSKEY';
    case 59:
      return 'CDS';
    case 37:
      return 'CERT';
    case 5:
      return 'CNAME';
    case 49:
      return 'DHCID';
    case 32769:
      return 'DLV';
    case 39:
      return 'DNAME';
    case 48:
      return 'DNSKEY';
    case 43:
      return 'DS';
    case 55:
      return 'HIP';
    case 13:
      return 'HINFO';
    case 45:
      return 'IPSECKEY';
    case 25:
      return 'KEY';
    case 36:
      return 'KX';
    case 29:
      return 'LOC';
    case 15:
      return 'MX';
    case 35:
      return 'NAPTR';
    case 2:
      return 'NS';
    case 47:
      return 'NSEC';
    case 50:
      return 'NSEC3';
    case 51:
      return 'NSEC3PARAM';
    case 12:
      return 'PTR';
    case 46:
      return 'RRSIG';
    case 17:
      return 'RP';
    case 24:
      return 'SIG';
    case 6:
      return 'SOA';
    case 99:
      return 'SPF';
    case 33:
      return 'SRV';
    case 44:
      return 'SSHFP';
    case 32768:
      return 'TA';
    case 249:
      return 'TKEY';
    case 52:
      return 'TLSA';
    case 250:
      return 'TSIG';
    case 16:
      return 'TXT';
    case 252:
      return 'AXFR';
    case 251:
      return 'IXFR';
    case 41:
      return 'OPT';
    case 255:
      return 'ANY';
  }

  return 'UNKNOWN_$type';
}
